### ISSUE TITLE
Don't have a version for Linux!

### ISSUE THREAD

**Issue by Tecnoll** [360modder/up-to-pypi#1]
Hi, I found your project on Pypi, and I loved its proposal, to facilitate sending Python packages to Pypi, but I noticed that it only works on Windows, could you make it cross-platform, please?

**Comment by 360modder** [comment]
The next pypi release would be platform independent. You can request some features if you want I will try to implement them.

**Comment by clitic** [comment]
@Tecnoll Now the master branch supports linux as per commit c8274991c9f79421036d5035cdfda5a7f9b3878a

Also a platform independent wheel is also released at pypi on 13/08/21.
